image: maven:4.0.0

variables:
 MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
 MAVEN_OPTS: "-Dmaven.repo.local*.m2/repository"

cache:
 paths:
  - .m2/repository/
  - target/



stages:
 - test
 - build
 - deploy
 
before_script:
 - chmod +x mvnw

test:
 stage: test
 script: ./mvnw test
 
build:
 stage: build
 script: ./mvnw package -DskipTests
 artifacts:
  paths:
   - target/gitlab-pipeline.jar

production:
 stage: deploy
 script:
  - echo "Deploy arquivo!"
 only:
  - main